import {
    LeftOutlined,
    HomeOutlined,
    LoginOutlined,
    SaveOutlined,
    PlaySquareOutlined,
    ContactsOutlined,
    EditOutlined,
    DeleteOutlined,
    CloseCircleOutlined,
    SettingOutlined,
    MessageOutlined,
    UserOutlined,
    ExclamationCircleOutlined,
    UploadOutlined,
    EnterOutlined,
    AudioTwoTone,
    FileImageTwoTone,
    PauseOutlined,
    SmileOutlined,
    CloseOutlined

} from "@ant-design/icons";

export default {
    DeleteOutlined,
    CloseCircleOutlined,
    EditOutlined,
    SettingOutlined,
    LeftOutlined,
    HomeOutlined,
    LoginOutlined,
    SaveOutlined,
    PlaySquareOutlined,
    ContactsOutlined,
    MessageOutlined,
    UserOutlined,
    ExclamationCircleOutlined,
    UploadOutlined,
    EnterOutlined,
    AudioTwoTone,
    FileImageTwoTone,
    PauseOutlined,
    SmileOutlined,
    CloseOutlined
};